---
title: "Predicting ICU mortality rates (IDA)"
author: "Debbie"
date: "2025-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Requirements}
library(readxl)
library(readr)
library(tidyverse)
library(skimr)
library(janitor)
library(dplyr)
library(forcats)
library(lubridate)
library(caret)
library(glmnet)
library(Matrix)
library(pROC)
library(rpart)
library(rpart.plot)
library(xgboost)
library(ggplot2)
library(gganimate)
library(transformr)
library(parsnip)
library(yardstick)
library(rpart.plot)
```

## Initial exploration
```{r Load and merge datasets}
train_y <- as_tibble(read_csv("mimic_train_y.csv")[,-1]) # remove column id, conversion into a tibble
train_X <- as_tibble(read_csv("mimic_train_X.csv")[,-1])
test_X <- as_tibble(read_csv("mimic_test_X.csv")[,-1])
metadata <- read_csv("MIMIC_metadata_diagnose.csv")

train_y %>% slice_head(n=5) # predictive outcome
train_X %>% slice_head(n=5) # predictive features
metadata %>% slice_head(n=5) # diagnosis with code 

train <- inner_join(train_X, train_y, by= "icustay_id")
train %>% slice_head(n=5)

glimpse(train)
glimpse(test_X)
```

## Data cleaning

```{r Checking for class imbalance}
prop.table(table(train_y$HOSPITAL_EXPIRE_FLAG)) 
```
 
```{r Checking for missing values}
train %>% summarise_all(~sum(is.na(.)))
test_X %>% summarise_all(~sum(is.na(.)))
```

## Handling categorical variables

```{r Checking the cardinality for categorical variables}
train %>% 
  select(GENDER:FIRST_CAREUNIT) %>% 
  summarise_all(n_distinct)

test_X %>% 
  select(GENDER:FIRST_CAREUNIT) %>% 
  summarise_all(n_distinct)
```

```{r Conversion of categorical variables into dummies}
train <- train %>% 
  mutate(as.data.frame(model.matrix(~0 + GENDER, data = cur_data()))) %>% 
  select(-GENDER) %>% 
  mutate(as.data.frame(model.matrix(~0, + ADMISSION_TYPE, data = cur_data()))) %>%
  select(-ADMISSION_TYPE) %>% 
  mutate(as.data.frame(model.matrix(~0 + INSURANCE, data = cur_data()))) %>% 
  select(-INSURANCE) %>% 
  mutate(as.data.frame(model.matrix(~0 + RELIGION, data = cur_data()))) %>% 
  select(-RELIGION) %>% 
  mutate(as.data.frame(model.matrix(~0, + MARITAL_STATUS, data = cur_data()))) %>% 
  select(-MARITAL_STATUS) %>% 
  mutate(as.data.frame(model.matrix(~0 + ETHNICITY, data = cur_data()))) %>% 
  select(-ETHNICITY) %>% 
  mutate(as.data.frame(model.matrix(~0 + FIRST_CAREUNIT, data= cur_data()))) %>% 
  select(-FIRST_CAREUNIT)

test_X <- test_X %>% 
  mutate(as.data.frame(model.matrix(~0 + GENDER, data = cur_data()))) %>% 
  select(-GENDER) %>% 
  mutate(as.data.frame(model.matrix(~0, + ADMISSION_TYPE, data = cur_data()))) %>%
  select(-ADMISSION_TYPE) %>% 
  mutate(as.data.frame(model.matrix(~0 + INSURANCE, data = cur_data()))) %>% 
  select(-INSURANCE) %>% 
  mutate(as.data.frame(model.matrix(~0 + RELIGION, data = cur_data()))) %>% 
  select(-RELIGION) %>% 
  mutate(as.data.frame(model.matrix(~0, + MARITAL_STATUS, data = cur_data()))) %>% 
  select(-MARITAL_STATUS) %>% 
  mutate(as.data.frame(model.matrix(~0 + ETHNICITY, data = cur_data()))) %>% 
  select(-ETHNICITY) %>% 
  mutate(as.data.frame(model.matrix(~0 + FIRST_CAREUNIT, data= cur_data()))) %>% 
  select(-FIRST_CAREUNIT)

train <- train %>% 
  select(-c(DIAGNOSIS))
test_X <- test_X %>% 
  select(-c(DIAGNOSIS))
```

## Exploring numerical variables

```{r Correlation matrix between numerical variables}
numeric_vars <- train %>%  
  select(-icustay_id, -subject_id, -hadm_id, -HOSPITAL_EXPIRE_FLAG) %>%
  select(where(is.numeric))
numeric_long <- numeric_vars %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

colnames(numeric_vars)

cor_matrix <- cor(numeric_vars, use = "pairwise.complete.obs")
corrplot::corrplot(cor_matrix, method = "color", tl.cex = 0.6)

high_corr_indices <- findCorrelation(cor_matrix, cutoff = 0.8)
names(numeric_vars)[high_corr_indices]
```
```{r Computing min max difference in vital signs}
train <- train %>%
  mutate(
    HeartRate_Diff = HeartRate_Max - HeartRate_Min,
    SysBP_Diff     = SysBP_Max - SysBP_Min,
    DiasBP_Diff    = DiasBP_Max - DiasBP_Min,
    MeanBP_Diff    = MeanBP_Max - MeanBP_Min,
    RespRate_Diff  = RespRate_Max - RespRate_Min,
    TempC_Diff     = TempC_Max - TempC_Min,
    SpO2_Diff      = SpO2_Max - SpO2_Min
  )
train_long_Diff <- train %>%
  select(HOSPITAL_EXPIRE_FLAG, ends_with("_Diff")) %>%
  pivot_longer(-HOSPITAL_EXPIRE_FLAG, names_to = "Variable", values_to = "Value")

ggplot(train_long_Diff, aes(x = as.factor(HOSPITAL_EXPIRE_FLAG), y = Value, fill = as.factor(HOSPITAL_EXPIRE_FLAG))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  facet_wrap(~ Variable, scales = "free", ncol = 2) +
  labs(x = "Mortality (0 = Alive, 1 = Death)", y = "Delta Value", title = "Vital Sign Variability by Mortality") +
  coord_cartesian(ylim = c(0, 100)) +
  theme_minimal() +
  theme(legend.position = "none")

```

## Feature engineering 

```{r Calculating age from admit time and DOB}
train <- train %>% mutate(
  Age = as.numeric(difftime(ADMITTIME, DOB, units = "days"))/ 365.25) %>%
  select(-c(ADMITTIME, DOB, Diff))

test_X <- test_X %>% mutate(
  Age = as.numeric(difftime(ADMITTIME, DOB, units = "days"))/ 365.25) %>% 
  select(-c(ADMITTIME, DOB, Diff))

summary(train$Age)
hist(train$Age)

summary(test_X$Age)
hist(test_X$Age)

train <- train %>% 
  mutate(Age = pmin(Age, 100))

test_X <- test_X %>% 
  mutate(Age = pmin(Age, 100))
```

```{r Target encoding to compute smoothed mortality rate for each ICD code}
# Baseline mortality rate 
av_deathrate <- sum(train$HOSPITAL_EXPIRE_FLAG) / length(train$HOSPITAL_EXPIRE_FLAG)

# Smoothing rate 
weight_av_deathrate <- 2  

# ICD specific smoothed death rate to push smaller groups towards the global mean 
deathrate <- train |> 
    group_by(ICD9_diagnosis) |>
    summarize(Mean = (sum(HOSPITAL_EXPIRE_FLAG) + weight_av_deathrate*av_deathrate)/(length(HOSPITAL_EXPIRE_FLAG) + weight_av_deathrate))

# Adding a column to store ICD death rate 
train <- train |>
  mutate(ICD9_DEATH_RATE = rep(NA, nrow(train)))

# Assigning each patient their ICD9 death rate 
for(i in 1:nrow(train)){
  train$ICD9_DEATH_RATE[i] <- deathrate$Mean[which(deathrate$ICD9_diagnosis == train$ICD9_diagnosis[i])]
}

# If ICD does not exist in the test set, the global death rate is used instead 
test_X <- test_X |>
  mutate(ICD9_DEATH_RATE = rep(NA, nrow(test_X)))

for(i in 1:nrow(test_X)){
  try(test_X$ICD9_DEATH_RATE[i] <- deathrate$Mean[which(deathrate$ICD9_diagnosis == test_X$ICD9_diagnosis[i])], silent = TRUE)
  if(is.na(test_X$ICD9_DEATH_RATE[i])){
    test_X$ICD9_DEATH_RATE[i] <- av_deathrate
  }
}

# Removing ICD9 code from both data sets 
train <- train |> 
  select(-c(ICD9_diagnosis))

test_X <- test_X |> 
  select(-c(ICD9_diagnosis))
```

```{r Alternate methods- Using keyword pattern matching to handle cardinality in diagnosis}
train <-train %>% 
           mutate(DIAGNOSIS = ifelse(is.na(DIAGNOSIS), "UNKNOWN", DIAGNOSIS)) %>% 
  add_count(DIAGNOSIS, name = 'freq') %>% # adding a frequency count 
  mutate(SHORT_GROUPED = case_when(
    
    grepl('resp|pneumon|bronch', DIAGNOSIS, ignore.case = TRUE) ~ 'Respiratory', 
    grepl('hemorrh|athrscl|aortic|valve|hrt|atrial|emblsm|infarct|AMI', DIAGNOSIS, ignore.case = TRUE) ~ 'Cardiovascular', 
    grepl('kidney|gastro|pancreat|colon|liver', DIAGNOSIS, ignore.case = TRUE) ~ 'GI', 
    grepl('neoplasm|mal neo|cancer', DIAGNOSIS, ignore.case = TRUE) ~ 'Neoplasms', 
    grepl('infection|septicemia|sepsis', DIAGNOSIS, ignore.case = TRUE) ~ 'Infectious diseases',
    freq >=20 ~ DIAGNOSIS, 
    TRUE ~ 'Other rare diseases')) 

n_distinct(train$DIAGNOSIS) - n_distinct(train$SHORT_GROUPED)

train %>%
  count(SHORT_GROUPED) %>%
  arrange(desc(n))

count(train$SHORT_GROUPED)
```


```{r Removing identifying columns}
train <- train |> 
  select(-c(subject_id, hadm_id, icustay_id)) # remove identifying columns 

test_icustay_id <- test_X |> 
  select(icustay_id)

test_X <- test_X |> 
  select(-c(subject_id, hadm_id, icustay_id))
```

```{r Cleaning variable names}
colnames(train) <- gsub(" ", "", colnames(train), fixed = TRUE)
colnames(test_X) <- gsub(" ", "", colnames(test_X), fixed = TRUE)
colnames(train) <- gsub("(", "", colnames(train), fixed = TRUE)
colnames(train) <- gsub(")", "", colnames(train), fixed = TRUE)
colnames(test_X) <- gsub("(", "", colnames(test_X), fixed = TRUE)
colnames(test_X) <- gsub(")", "", colnames(test_X), fixed = TRUE)
```

```{r Standardization of numeric predictors}
train_X <- train |>
  select(where(is.numeric)) %>%
  select(-HOSPITAL_EXPIRE_FLAG)

test_X <- test_X %>%
  select(where(is.numeric)) 

# Dropping unnecessary columns 
cols_train_drop <- c("...1.x", "...1.y")
cols_test_drop <- c("...1")

# Ensure exact matching with the column names
train_X <- train_X %>% select(-all_of(cols_train_drop))
test_X <- test_X %>% select(-all_of(cols_test_drop))

means <- apply(train_X, 2, mean)
sds <- apply(train_X, 2, sd)

train_X_sd <- train_X |>
 scale(center = means, scale = sds) |>  as_tibble()
test_X_sd <- test_X |>
  scale(center = means, scale = sds) |>
    as_tibble()

# Manual way for more fine grained control

# train_X_sd <- train_X
# test_X_sd <- test_X 
# for(j in 1:ncol(train_X)){
#   train_X_sd[,j] <- (train_X_sd[,j] - means[j])/sds[j]
#   test_X_sd[,j] <- (test_X_sd[,j] - means[j])/sds[j]
# }

# Adding the target variable back to the standardized training set 
train <- train_X_sd |>
  mutate(HOSPITAL_EXPIRE_FLAG = train$HOSPITAL_EXPIRE_FLAG)
```
